exploits_dir: "/home/ossigeno/Github/Ansem/testExpl/"
tick: 5
team_dir : "/home/ossigeno/Github/Ansem/teams/"
gameserver: "localhost:4444"
threshold: 10
#gameserver: "submission.faustctf.net:666"
workers: 8
submission_type: "nc"
flag_regex: "C.*"
#flag_regex: "ğŸ³ï¸\u200dğŸŒˆ\\X{4}"

# flag_regex: "FAUST_[A-Za-z0-9/+]{32}"
flag_accepted: "DIOCANE"
token: "some_kind_of_token"
timeout: 8
